# This is a basic workflow to help you get started with Actions

name: mainProcess

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: '0 0/6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: auto-run
        run: |
          bash start.sh &
          sleep 5h
          sleep 50m
          bash stop.sh
          kill %1
      - name: GitHub Commit & Push
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  
