# This is a basic workflow to help you get started with Actions

name: frp

# Controls when the action will run. 
on:
  workflow_dispatch:
  
jobs:
  pre:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2  
      - name: 拉取
        run: |
          rm -r frp
          wget https://github.com/fatedier/frp/releases/download/v0.37.1/frp_0.37.1_linux_amd64.tar.gz 
          tar -zxvf frp_0.37.1_linux_amd64.tar.gz
          mv frp_0.37.1_linux_amd64 frp
          rm frp_0.37.1_linux_amd64.tar.gz
        
      - name: push
        uses: actions-x/commit@v2
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
