# This is a basic workflow to help you get started with Actions

name: frp

# Controls when the action will run. 
on:
  workflow_dispatch:
  
jobs:
  pre:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2  
      - name: 拉取
        run: |
          rm -r frp
          wget "https://down.oray.com/hsk/linux/phddns_5.2.0_amd64.deb" -O phddns_5.2.0_amd64.deb
          rm *.sh
        
      - name: push
        uses: actions-x/commit@v2
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
